### ISSUE TITLE
Cannot forward message

### ISSUE THREAD

**Issue by ccykevin** [gram-js/gramjs#115]
RPCError: CHANNEL_INVALID
    at Object.RPCMessageToError (C:\nodejs\telegram-bot\node_modules\telegram\errors\index.js:24:12)
    at MTProtoSender._handleRPCResult (C:\nodejs\telegram-bot\node_modules\telegram\network\MTProtoSender.js:487:36)
    at MTProtoSender.<anonymous> (C:\nodejs\telegram-bot\node_modules\telegram\network\MTProtoSender.js:411:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\nodejs\telegram-bot\node_modules\telegram\network\MTProtoSender.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined
}

**Comment by painor** [comment]
what code caused that ? the error on it's own isn't very helpful.

**Comment by ccykevin** [comment]
thanks for ur help

Im using "telegram": "^1.7.15"

`client.addEventHandler(autoForward, new NewMessage({}));
  async function autoForward(event: NewMessageEvent) {
    try {
      const message = event.message;
      const result = await message.forwardTo(new Api.PeerChannel({ channelId: id }));
      console.log(result);
    } catch (e) {
      console.log(e);
    }
  }`

I'm pretty sure the id was correct

**Comment by ccykevin** [comment]
even forward to me have same error

client.addEventHandler(autoForward, new NewMessage({}));
  async function autoForward(event: NewMessageEvent) {
    try {
      const message = event.message;
      message.forwardTo("me");
    } catch (e) {
      console.log(e);
    }
  }

**Comment by painor** [comment]
I don't think the error is coming from there. 
I've just tried your code and it worked fine. What is id ?
And you need to await it if you want to catch the error
`await message.forwardTo("me");`

**Comment by ccykevin** [comment]
I found out that not every group/channel message can use the forward function, some of them work some donnot, but I don't know the reason, because the some of them will cause these exception

**Comment by painor** [comment]
> I found out that not every group/channel message can use the forward function, some of them work some donnot, but I don't know the reason, because the some of them will cause these exception

There are two possible reasons. either it's the wrong ID or the library never saw them. Try using client.getDialogs() at the start and see

**Comment by ccykevin** [comment]
> > I found out that not every group/channel message can use the forward function, some of them work some donnot, but I don't know the reason, because the some of them will cause these exception
> 
> There are two possible reasons. either it's the wrong ID or the library never saw them. Try using client.getDialogs() at the start and see

`await message.forwardTo("me");`

it should not be a problem, I don't think that is the reason, but if not one report the same issues, it might be my problem, because I'm using the same ID to send the message it works perfectly

**Comment by painor** [comment]
> > > I found out that not every group/channel message can use the forward function, some of them work some donnot, but I don't know the reason, because the some of them will cause these exception
> > 
> > 
> > There are two possible reasons. either it's the wrong ID or the library never saw them. Try using client.getDialogs() at the start and see
> 
> `await message.forwardTo("me");`
> 
> it should not be a problem, I don't think that is the reason, but if not one report the same issues, it might be my problem, but I'm using the same ID to send the message it works perfectly

No one has reported the same issue yet still could be a library bug but I coudln't reprdouce. Are you using StringSession or StoreSession?

**Comment by ccykevin** [comment]
> > > > I found out that not every group/channel message can use the forward function, some of them work some donnot, but I don't know the reason, because the some of them will cause these exception
> > > 
> > > 
> > > There are two possible reasons. either it's the wrong ID or the library never saw them. Try using client.getDialogs() at the start and see
> > 
> > 
> > `await message.forwardTo("me");`
> > it should not be a problem, I don't think that is the reason, but if not one report the same issues, it might be my problem, but I'm using the same ID to send the message it works perfectly
> 
> No one has reported the same issue yet still could be a library bug but I coudln't reprdouce. Are you using StringSession or StoreSession?

Im using StringSession
