### ISSUE TITLE
How to handle registration when logging in?

### ISSUE THREAD

**Issue by ghost** [gram-js/gramjs#144]
I use these codes:
```typescript
import { TelegramClient } from 'telegram'
import { StringSession }  from 'telegram/sessions'
import input from 'input'; // npm i input

const apiId = 123456
const apiHash = '123456abcdfg'
const stringSession = new StringSession(''); // fill this later with the value from session.save()
(async () => {
    console.log('Loading interactive example...');
    const client = new TelegramClient(stringSession, apiId, apiHash, { connectionRetries: 5 });
    await client.start({
        phoneNumber: async () => await input.text('number ?'),
        password: async () => await input.text('password?'),
        phoneCode: async () => await input.text('Code ?'),
        onError: (err) => console.log(err),
    });
    console.log('You should now be connected.');
    console.log(client.session.save()) // Save this string to avoid logging in again
    await client.sendMessage('me', { message: 'Hello!' });
})()
```
If the mobile phone number has not been registered, the following problems will be reported:
```
api.js:402 CastError: Found wrong type for lastName. expected string but received undefined.If you think this is a mistake please report it.
    at VirtualClass.assertType (api.js:403)
    at VirtualClass.validate (api.js:345)
    at VirtualClass.getBytes (api.js:412)
    at new RequestState (RequestState.ts:20)
    at MTProtoSender.send (MTProtoSender.ts:278)
    at Object.<anonymous> (users.ts:35)
    at Generator.next (<anonymous>)
    at fulfilled (VM3103 users.js:5)
```

At this time, I must use `client.disconnect()`, otherwise it will continue to loop and cause memory leaks

**Comment by pythonjsgo** [comment]
Hello, I have same promblem, please show how you passed name parameters.
My code: 

```
    await client.start({
        phoneNumber: '+'+resp.number.toString(),
        //phoneCode: async () => await sms.getCode(resp.id),
        phoneCode: async () => await input.text('code:'),
        firstName: 'Testname',
        lastName: 'Testlastname',
        onError: (err) => console.log(err),

    });
```
After entering code facing error
```

CastError: Found wrong type for lastName. expected string but received undefined.If you think this is a mistake please report it.
    at VirtualClass.assertType (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/api.js:353:43)
    at VirtualClass.validate (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/api.js:299:30)
    at VirtualClass.getBytes (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/api.js:360:26)
    at new RequestState (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/network/RequestState.js:9:29)
    at MTProtoSender.send (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/network/MTProtoSender.js:197:23)
    at Object.invoke (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/users.js:27:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.signInUser (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:150:35)
    at async _authFlow (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:338:11)
    at async Object.start (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:41:5)
TypeError: Cannot read properties of undefined (reading 'constructor')
    at serializeBytes (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/generationHelpers.js:238:60)
    at argToBytes (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/api.js:105:20)
    at VirtualClass.getBytes (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/tl/api.js:412:42)
    at new RequestState (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/network/RequestState.js:9:29)
    at MTProtoSender.send (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/network/MTProtoSender.js:197:23)
    at Object.invoke (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/users.js:27:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.signInUser (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:150:35)
    at async _authFlow (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:338:11)
    at async Object.start (/home/navalny/PROJ/node/telegram_autoreger/node_modules/telegram/client/auth.js:41:5)
CastError: Found wrong type for lastName. expected string but received undefined.If you think this is a mistake please report it.
```

**Comment by trizau** [comment]
I used **firstAndLastNames** to set the username
like this
```typescript
await client.start({
     phoneNumber: this.phone,
     password: async () => {
         // ...
     },
     phoneCode: () => {// if need verify code
         // ...
     },
     onError: (err: Error) => {
         // ...
     },
     firstAndLastNames: async () => {
         return ['firstName','lastName']
     }
});
```
