### ISSUE TITLE
node js version compatibility

### ISSUE THREAD

**Issue by detj** [gram-js/gramjs#17]
## Problem

Throws error when used with node 10.x.x because node 10 doesn't support static class fields.

```
static DEFAULT_OPTIONS = {
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/private/tmp/telegram-try/node_modules/telegram/gramjs/index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
## Solution

Either the source should be transpiled to ES5 syntax on postinstall so that it runs in most JavaScript environments or add an [**engines**](https://docs.npmjs.com/files/package.json#engines) field to package.json mentioning compatible node versions.

**Note:** Works fine with node 12.x.x

**Comment by YouTwitFace** [comment]
@detj @painor is switching to TypeScript which will transpile it.

**Comment by YouTwitFace** [comment]
@painor is switching it to TypeScript which will transpile it.

**Comment by AndrewLaneX** [comment]
Please check if this is still an issue. If so, feel free to re-open this issue.
