### ISSUE TITLE
npx tgsession unable to generate session string

### ISSUE THREAD

**Issue by lynvi** [gram-js/gramjs#207]
```
RPCError: 406: UPDATE_APP_TO_LOGIN (caused by auth.SendCode)
    at Object.RPCMessageToError (/home/abkader/.npm/_npx/81089/lib/node_modules/tgsession/node_modules/telegram/errors/index.js:24:12)
    at MTProtoSender._handleRPCResult (/home/abkader/.npm/_npx/81089/lib/node_modules/tgsession/node_modules/telegram/network/MTProtoSender.js:481:36)
    at MTProtoSender._processMessage (/home/abkader/.npm/_npx/81089/lib/node_modules/tgsession/node_modules/telegram/network/MTProtoSender.js:406:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MTProtoSender._recvLoop (/home/abkader/.npm/_npx/81089/lib/node_modules/tgsession/node_modules/telegram/network/MTProtoSender.js:382:17) {
  code: 406,
  errorMessage: 'UPDATE_APP_TO_LOGIN'
```

**Comment by CelliHere** [comment]
I'm having the same issue. This seems to happens with newly created TG Accounts which need to use 64-Bit-IDs. Any idea when there is a fix out for that? Thanks a ton!

**Comment by rojserbest** [comment]
The package maintainer should update GramJS in order to fix it.

**Comment by rojserbest** [comment]
@Gowtham2003

**Comment by rojserbest** [comment]
I also have a web app which generates the string session in your browser: ssg.rojser.best.

**Comment by Gowtham2003** [comment]
I'll update and publish soon

**Comment by Gowtham2003** [comment]
I have update the packages and published the changes 

Now it should work

**Comment by lynvi** [comment]
Thank you 🙌
