### ISSUE TITLE
Problem when flood = new Cls({ request: request, capture: capture }

### ISSUE THREAD

**Issue by jenaze** [gram-js/gramjs#220]
I Got this Error
```
C:\tbot\node_modules\telegram\errors\index.js:21
            return new Cls({ request: request, capture: capture });
                   ^

FloodWaitError: A wait of 416 seconds is required (caused by InvokeWithLayer)
    at Object.RPCMessageToError (C:\tbot\node_modules\telegram\errors\index.js:21:20)
    at MTProtoSender._handleRPCResult (C:\tbot\node_modules\telegram\network\MTProtoSender.js:481:36)
    at MTProtoSender._processMessage (C:\tbot\node_modules\telegram\network\MTProtoSender.js:406:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (C:\tbot\node_modules\telegram\network\MTProtoSender.js:382:17) {
  code: 420,
  errorMessage: 'FLOOD',
  seconds: 416
}
```

**Comment by painor** [comment]
Telegram is having some network issues currently maybe this is because of that?

**Comment by jenaze** [comment]
> Telegram is having some network issues currently maybe this is because of that?

No I think This is a Unhandled Exception for Create A new Cls

**Comment by painor** [comment]
The error is in the line under it. 
Telegram returns theses errors. 
`FloodWaitError: A wait of 416 seconds is required (caused by InvokeWithLayer)`
