### ISSUE TITLE
It's taking 2 attempts to upload a file

### ISSUE THREAD

**Issue by sanjar12** [gram-js/gramjs#228]
I'm trying to upload ~1mb file using sendFile and/or uploadFile methods.  When I call these functions, it starts to connect to :443 port of current host. Then after some timeout it disconnects from that host and then attempts to connect again, and after that my file is being successfully sent. And every time it takes 2 attempts to send a file.
I also tried to manually send the file rewriting uploadFile function, and it fails on 
```
sender = await client.getSender(
     client.session.dcId
);
```
line. 

Here's the logs that I'm getting:

```
[2022-01-05T15:34:03.952Z] [INFO] - [Running gramJS version 2.0.14]
[2022-01-05T15:34:03.958Z] [INFO] - [Connecting to 149.154.167.51:80/TCPFull...]
[2022-01-05T15:34:04.051Z] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!]   <-- it's connecting to :80 port when started
sending a file
[2022-01-05T15:34:04.735Z] [INFO] - [Connecting to 149.154.167.50:443/TCPFull...]
[2022-01-05T15:34:04.833Z] [INFO] - [Connection to 149.154.167.50:443/TCPFull complete!] <--- first attempt, connecting to :443 port

[2022-01-05T15:34:34.835Z] [INFO] - [Disconnecting from 149.154.167.50:443/TCPFull...]   <--- first attempt failed
Error: Disconnect
    at ~\node_modules\telegram\extensions\MessagePacker.js:106:33
    at Array.forEach (<anonymous>)
    at MessagePacker.rejectAll (~\node_modules\telegram\extensions\MessagePacker.js:105:29)
    at MTProtoSender._disconnect (~\node_modules\telegram\network\MTProtoSender.js:245:25)
    at MTProtoSender.disconnect (~\node_modules\telegram\network\MTProtoSender.js:166:20)
    at Timeout._onTimeout (~\node_modules\telegram\client\telegramBaseClient.js:253:20)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

[2022-01-05T15:34:34.851Z] [INFO] - [Connecting to 149.154.167.50:443/TCPFull...]
[2022-01-05T15:34:34.852Z] [INFO] - [connection closed]
[2022-01-05T15:34:34.946Z] [INFO] - [Connection to 149.154.167.50:443/TCPFull complete!] <--- second attempt
file sent successfully...
```

Is it a known problem, or am I doing something wrong?

**Comment by painor** [comment]
are you setting the correct size ? can you try updating to latest version and see if it's happening?

**Comment by sanjar12** [comment]
Yes, I'm setting correct size, and it's uploading on second attempt.
I updated to latest version, same issue remains.

On the first connection progress stuck at 0, and after second reconnection it's actually starting to upload and progress changes.
I think there's some connection issues are happening on first try, and after reconnecting it's resolving.

Also I dig deeper and changed EXPORTED_SENDER_RELEASE_TIMEOUT from 30 sec into 1 sec in "async _borrowExportedSender" function. After first reconnecting it's actually sending a file.

I'll try dig deeper again, and if you have any suggestions I'll try that out. thanks

**Comment by sanjar12** [comment]
So I checked with debug logs enabled and adding my own loggers inside.
When I send normal message through sender like this:
```
       let sender = await client.getSender(client.session.dcId);
        await sender.send(new Api.messages.SendMessage({
            peer: new Api.InputPeerUser({ userId:"someUserId" }),
            message: "Some message!",
            randomId: BigInt("-4156859812595"),
          }));
          
```
It's actually sending the message but when I send a file part using SaveBigFilePart method it's not sending.
Only difference here is, when sending message, it logs 
```
[Handling bad salt for message _msg_id_] 
[1 message(s) will be resent]

```
where msg_id is actually assigned msg_id to sendMessage request.

but when sending filePart it logs something like this:
```
[Handling bad salt for message _msg_id_] 
[0 message(s) will be resent]
```
where we didn't assigned any message/request with _msg_id_ and it's not in _pendingState queue. I think that's why it's not sending anything and stuck there

@painor  can you take a look and give suggestions ?

**Comment by karpotkin** [comment]
[painor](https://github.com/painor) same issue, but when I'm trying to download the file (client.downloadFile):
```
const mediaBuf = await client.downloadFile(
  new Api.InputPhotoFileLocation(location),
  { dcId: photo.dcId }
);
```

Error Trace:
```
Error: Disconnect
  at /node_modules/telegram/extensions/MessagePacker.js:106:33
  at Array.forEach (<anonymous>)
  at MessagePacker.rejectAll (/node_modules/telegram/extensions/MessagePacker.js:105:29)
  at MTProtoSender._disconnect (/node_modules/telegram/network/MTProtoSender.js:247:25)
  at MTProtoSender.disconnect (/node_modules/telegram/network/MTProtoSender.js:168:20)
  at MTProtoSender._reconnect (/node_modules/telegram/network/MTProtoSender.js:728:24)
  at /node_modules/telegram/network/MTProtoSender.js:721:22
```

<img width="740" alt="Screenshot 2022-04-21 at 09 39 52" src="https://user-images.githubusercontent.com/5529387/164389996-8d8c1fe2-33a2-4bf0-abc0-2763dec8a476.png">
