### ISSUE TITLE
Cannot cast to any kind of peer

### ISSUE THREAD

**Issue by Gercov** [gram-js/gramjs#272]
It stopped working all of a sudden when everything was fine. When I try to get information about a channel, it throws an error:
```
Error: Cannot cast ateobreaking to any kind of peer
    at _raiseCastFail (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\Utils.ts:50:11)
    at Object.getPeer (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\Utils.ts:991:9)
    at Object.getInputEntity (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\client\users.ts:293:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getInputFromResolve (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\tl\api.js:153:42)
    at async VirtualClass.resolve (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\tl\api.js:569:41)
    at async Object.invoke (C:\Users\Александр\Desktop\dev\TeleAD\telegram\node_modules\gramjs\client\users.ts:32:5)
```

```
export const telegramStart = async () => {
  try {
    await client.start({
      botAuthToken: botAuthToken,
    });
    await client.connect();

    const result = await client.invoke(
      new Api.channels.GetFullChannel({
        channel: "ateobreaking",
      })
    );
    console.log(result);
  } catch (e) {
    console.log(e);
  }
};
```

**Comment by painor** [comment]
you are probably receiving that because telegram has limited how many times you can call that function (username resolving),

**Comment by Gercov** [comment]
@painor Do I need to create a new bot account?

**Comment by painor** [comment]
> @painor Do I need to create a new bot account?

Or wait until the floodwait is over, you can use await client.getEntity(username) to know the exact time I guess

**Comment by Gercov** [comment]
@painor its really work. Where can i read more about restrictions?

**Comment by roj1512** [comment]
No one knows about those precisely.

**Comment by Gercov** [comment]
@roj1512 I need to scan 100-200 thousand channels every hour to get posts, what should I do in this case?

**Comment by roj1512** [comment]
Use multiple accounts and have a delay between calling the methods, or simply just face floodwaits.

**Comment by roj1512** [comment]
No.

- Bot’s cannot fetch messages.
- A single account can create a maximum of 20 bots.

**Comment by painor** [comment]
You should also not use usernames but IDs

**Comment by Gercov** [comment]
@painor But I used to use usernames. It was a flood

**Comment by Gercov** [comment]
@roj1512 I made an algorithm that allows you to receive community posts using a bot. Now the main problem is in the flood. I checked another bot created on my account, there is also a flood. Looks like I'll have to do something differently.
