### ISSUE TITLE
After using client.destroy or client.disconnect client is still working

### ISSUE THREAD

**Issue by jasonhutton-sd** [gram-js/gramjs#289]
The disconnect and destroy methods do not seem to work.

**Comment by jasonhutton-sd** [comment]
I have let it sit for a few minutes and it just does not give up:
Destroyed! <- console log from destroy promise 
Logger.js:119 [2022-03-22T19:33:58.223Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:33:58.224Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:34:25.113Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:34:25.113Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:34:55.189Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:34:55.189Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:35:25.268Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:35:25.269Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:35:55.309Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:35:55.310Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:36:25.393Z] [INFO] - [Running gramJS version 2.5.20]
Logger.js:119 [2022-03-22T19:36:25.393Z] [INFO] - [Running gramJS version 2.5.20]

**Comment by jasonhutton-sd** [comment]
Now getting this:
Error: Cannot send requests while disconnected. You need to call .connect()
    at MTProtoSender.send (MTProtoSender.js:197:1)
    at updates.js:160:1
    at attempts (updates.js:200:1)
    at async Object._updateLoop (updates.js:159:1)

Any way to suppress this? It breaks my app after a disconnect.
Thanks
