### ISSUE TITLE
Problem with messages.SendMedia

### ISSUE THREAD

**Issue by BaalDev-Solutions** [gram-js/gramjs#325]
Hi everyone, 

I am trying to use the method message.sendMedia and I am getting the next error:

`
[2022-05-19T02:37:29.083] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
Error: Disconnect (caused from messages.SendMedia)
    at /Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/extensions/MessagePacker.js:107:33
    at Array.forEach (<anonymous>)
    at MessagePacker.rejectAll (/Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/extensions/MessagePacker.js:105:29)
    at MTProtoSender._disconnect (/Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/network/MTProtoSender.js:249:25)
    at MTProtoSender.disconnect (/Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/network/MTProtoSender.js:168:20)
    at TelegramClient.disconnect (/Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/client/telegramBaseClient.js:163:32)
    at _updateLoop (/Users/apple/Desktop/Projects/Telegram-Bots/gram-js/node_modules/telegram/client/updates.js:177:26)
[2022-05-19T02:37:29.086] [INFO] - [Connecting to 149.154.167.91:80/TCPFull using PromisedNetSocket]`

I am also having problem with channels.EditPhoto which also uses a files.

Does anyone know if this is a problem of the library?

**Comment by BaalDev-Solutions** [comment]
Anyone?

**Comment by k1zn** [comment]
Same problem.

**Comment by painor** [comment]
did this happen recently? can you try an older version of the library (2.6.X)

**Comment by k1zn** [comment]
@painor I install telegram@[2.6.13](https://www.npmjs.com/package/telegram/v/2.6.13) and this problem is gone.

**Comment by BaalDev-Solutions** [comment]
@painor, @k1zn  What do you mean by telegram@2.6.13? The version of telegram installed in the computer?

**Comment by k1zn** [comment]
yes, just do `npm i telegram@2.6.13`

**Comment by BaalDev-Solutions** [comment]
It worked,

Thanks a lot!

**Comment by k1zn** [comment]
But I think that this is only a temporary solution to the problem, since you need to understand why this is happening on the latest version. This message is addressed to the developers.

**Comment by painor** [comment]
This commit should have fixed it https://github.com/gram-js/gramjs/commit/b99879464cd1114d89b333c5d929610780c4b003
