### ISSUE TITLE
TypeError: Cannot read property 'SUBCLASS_OF_ID' of undefined

### ISSUE THREAD

**Issue by vitorhariel** [gram-js/gramjs#34]
I'm running this on my code:

```js
const responseParticipants = await this.gramBot.invoke(
    new functions.channels.GetParticipantsRequest({
      channel: chat_id,
      filter: new types.ChannelParticipantsRecent(),
    }),
  );
```

However, while this works on my local computer, in my VPS, I always get this error:

```
TypeError: Cannot read property 'SUBCLASS_OF_ID' of undefined
    at Object.getPeer (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/Utils.js:304:18)
    at TelegramClient.getInputEntity (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/client/TelegramClient.js:800:22)
    at GetParticipantsRequest.resolve (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/tl/functions/channels.js:253:59)
    at TelegramClient.invoke (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/client/TelegramClient.js:253:23)
    at Timeout._onTimeout (/home/ninja/monetizze-gram/src/bot.js:49:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:20700) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of undefined
    at _raiseCastFail (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/Utils.js:13:43)
    at Object.getPeer (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/Utils.js:333:5)
    at TelegramClient.getInputEntity (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/client/TelegramClient.js:800:22)
    at GetParticipantsRequest.resolve (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/tl/functions/channels.js:253:59)
    at TelegramClient.invoke (/home/ninja/monetizze-gram/node_modules/telegram/gramjs/client/TelegramClient.js:253:23)
    at Timeout._onTimeout (/home/ninja/monetizze-gram/src/bot.js:49:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:20700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

I have no idea why this is happening.

**Comment by vitorhariel** [comment]
Nevermind, it was my mistake. I was mistakenly passing "undefined" to the channel param.
