### ISSUE TITLE
SESSION_PASSWORD_NEEDED

### ISSUE THREAD

**Issue by Vo0oX** [gram-js/gramjs#360]
**everything worked perfectly, I decided to switch to another user and I catch an error**

```

RPCError: 401: SESSION_PASSWORD_NEEDED (caused by auth.SignIn)
    at RPCMessageToError (/telegram/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/telegram/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/telegram/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/telegram/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 401,
  errorMessage: 'SESSION_PASSWORD_NEEDED'
}

```

**Comment by Vo0oX** [comment]
c2a955b09f84d356cb
SESSION_PASSWORD_NEEDED
/Users/user/Desktop/наработки/РАЗНОЕ/for_ training — telegram/node_modules/telegram/client/auth.js:300
            const password = await authParams.password(passwordSrpResult.hint);
                                              ^

TypeError: authParams.password is not a function
    at Object.signInWithPassword (/Users/user/Desktop/наработки/РАЗНОЕ/for_ training — telegram/node_modules/telegram/client/auth.js:300:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/user/Desktop/наработки/РАЗНОЕ/for_ training — telegram/app.js:145:29

Process finished with exit code 1

**Comment by painor** [comment]
password needs to be a function callback.

password: (hint)=>{ return req.body.password }
