### ISSUE TITLE
CastError: Found wrong type for gA. expected buffer but received undefined

### ISSUE THREAD

**Issue by huco95** [gram-js/gramjs#441]
I having some problems while trying to confirm the call. The `gAhash` is working fine for the request call but not for confirming it. If you see the trace it says that gA is undefined but it's not. 

Thanks!

Code:

```javascript
const { Api, TelegramClient } = require("telegram");
const { sha256, generateRandomBytes, sleep } = require("telegram/Helpers");
const { StringSession } = require("telegram/sessions");
const input = require("input");

const apiId = ;
const apiHash = "";
const session = new StringSession(
  ""
);
const client = new TelegramClient(session, apiId, apiHash, {});

function int_256_to_bytes(int) {
  const bytesArray = [];
  for (let i = 0; i < 32; i++) {
    let shift = int >> BigInt(8 * i);
    shift &= BigInt(255);
    bytesArray[i] = Number(String(shift));
  }
  return Buffer.from(bytesArray);
}

(async function run() {
  await client.connect(); // This assumes you have already authenticated with .start()

  // -------------------------------------
  const dhc = await client.invoke(
    new Api.messages.GetDhConfig({
      version: 0,
      randomLength: 256,
    })
  );

  const g = BigInt(dhc.g);
  const p = BigInt(`0x${dhc.p.toString("hex")}`);
  let a = BigInt(0);
  while (a <= 1 && a >= p) {
    a = BigInt(`0x${generateRandomBytes(256).toString("hex")}`);
  }

  const g_a = g ** a % p;
  const shag_a = await sha256(int_256_to_bytes(g_a));
  // -------------------------------------

  const phoneCall = await client.invoke(
    new Api.phone.RequestCall({
      userId: "@user",
      randomId: Math.floor(Math.random() * 10000),
      gAHash: shag_a,
      protocol: new Api.PhoneCallProtocol({
        minLayer: 92,
        maxLayer: 92,
        libraryVersions: ["3.0.0"],
        udpP2p: true,
        udpReflector: true,
      }),
      video: true,
    })
  );

  await client.invoke(
    new Api.phone.ConfirmCall({
      peer: new Api.InputPhoneCall({
        id: phoneCall.phoneCall.id,
        accessHash: phoneCall.phoneCall.accessHash,
      }),
      gAHash: shag_a,
      keyFingerprint: phoneCall.phoneCall.accessHash,
      protocol: new Api.PhoneCallProtocol({
        minLayer: 92,
        maxLayer: 92,
        libraryVersions: ["3.0.0"],
        udpP2p: true,
        udpReflector: true,
      }),
    })
  );
})();

```

Trace:

```
CastError: Found wrong type for gA. expected buffer but received undefined.If you think this is a mistake please report it.
    at VirtualClass.assertType (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\tl\api.js:352:43)
    at VirtualClass.validate (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\tl\api.js:298:30)
    at VirtualClass.getBytes (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\tl\api.js:359:26)
    at new RequestState (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\network\RequestState.js:9:29)
    at MTProtoSender.send (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\network\MTProtoSender.js:203:23)
    at Object.invoke (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\client\users.js:31:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    
    at async run (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\call.ode\node_modules\telegram\network\MTProtoSender.js:203:23)
    at Object.invoke (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\node_modules\telegram\client\users.js:31:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    
    at async run (C:\Users\fenos\OneDrive\Documentos\Proyectos\TelgramCall\node\call.js:63:3)

Node.js v18.12.1
```

**Comment by painor** [comment]
ConfirmCall has no gAHash param. It's called gA instead. 
I don't understand what you are trying to do exactly. if you want actual calls (with voice etc) then you'll need to use https://github.com/tgcalls-next/tgcalls
