### ISSUE TITLE
Required object location of upload.GetFileHashes is undefined

### ISSUE THREAD

**Issue by zjmqlf** [gram-js/gramjs#463]
```js
const { TelegramClient } = require("telegram");
const { Api } = require("telegram/tl");
const { StringSession } = require("telegram/sessions");
const { getFileInfo } = require("telegram/Utils");

const apiId = 0;
const apiHash = "";
const sessionString = "";
const client = await new TelegramClient(new StringSession(sessionString), apiId, apiHash, {
  connectionRetries: Number.MAX_VALUE,
  downloadRetries: 5,
  useWSS: false
});

for await (const message of client.iterMessages(
  "me", 
  {
    limit: 20,
    reverse: false,
    addOffset: 0,
    filter: Api.InputMessagesFilterVideo,
    waitTime: 60,
  })
) {
  if (message.media) {
    if (message.media.document) {
      const info = getFileInfo(message.media);
      console.log(info);
      const result = await client.invoke(new Api.upload.GetFileHashes({
        location: info,
        offset: message.id,
      }));
      console.log(result);
    } 
  }
}
```
I want to use GetFileHashes to query the HASH of the file to confirm whether it has been downloaded before, but an error has occurred.Return the following:
D:\test\tg_login\node_modules\telegram\tl\api.js:111
                throw new Error(`Required object ${argName} of ${requestName} is undefined`);
Error: Required object location of upload.GetFileHashes is undefined
    at argToBytes (D:\test\tg_login\node_modules\telegram\tl\api.js:111:23)
    at VirtualClass.getBytes (D:\test\tg_login\node_modules\telegram\tl\api.js:415:42)
    at new RequestState (D:\test\tg_login\node_modules\telegram\network\RequestState.js:9:29)
    at MTProtoSender.send (D:\test\tg_login\node_modules\telegram\network\MTProtoSender.js:203:23)
    at Object.invoke (D:\test\tg_login\node_modules\telegram\client\users.js:31:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (D:\test\tg_login\test.js:206:26)

**Comment by SecurityAndStuff** [comment]
```ts
  if (message.media) {
    if (message.media.document) {
      const info = getFileInfo(message.media);
      console.log(info);
      const result = await client.invoke(new Api.upload.GetFileHashes({
        location: info.location,
      }));
      console.log(result);
    } 
  }
}
```

**Comment by zjmqlf** [comment]
@SecurityAndStuff
I thought so at first, but I returned to LOCATION_ INVALID.

D:\test\tg_login\node_modules\telegram\errors\index.js:28
    return new RPCBaseErrors_1.RPCError(rpcError.errorMessage, request, rpcError.errorCode);
RPCError: 400: LOCATION_INVALID (caused by upload.GetFileHashes)
    at RPCMessageToError (D:\test\tg_login\node_modules\telegram\errors\index.js:28:12)
    at MTProtoSender._handleRPCResult (D:\test\tg_login\node_modules\telegram\network\MTProtoSender.js:517:58)
    at MTProtoSender._processMessage (D:\test\tg_login\node_modules\telegram\network\MTProtoSender.js:442:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (D:\test\tg_login\node_modules\telegram\network\MTProtoSender.js:418:17) {
  code: 400,
  errorMessage: 'LOCATION_INVALID'
}

**Comment by SecurityAndStuff** [comment]
Maybe it’s using one of the deprecated ones.

https://core.telegram.org/type/InputFileLocation

From looking at Utils.ts, it’s possible. Can you show info.className?

**Comment by zjmqlf** [comment]
@SecurityAndStuff
The value of info is:
{
  dcId: 1,
  location: {
    CONSTRUCTOR_ID: 3134223748,
    SUBCLASS_OF_ID: 354669666,
    className: 'InputDocumentFileLocation',
    classType: 'constructor',
    id: Integer { value: 4999435764694516515n },
    accessHash: Integer { value: 7045503851056973381n },
    fileReference: <Buffer 02 4c e2 ba f6 00 00 9a 01 63 b3 c9 d1 10 da ae f0 46 d0 af 36 fb 7d 02 f9 fd 79 39 77>,
    thumbSize: ''
  },
  size: Integer { value: 275047202n }
}

**Comment by SecurityAndStuff** [comment]
@zjmqlf can you upload the file that’s causing the error?

**Comment by SecurityAndStuff** [comment]
It's because the file is in another DC. You can verify this with `client.session.dcId`. Default is 4.

**Comment by jpdh9881** [comment]
For anyone having trouble switching data centres, use client.invokeWithSender instead of client.invoke. The sender will take care of switching data centres.
```
const sender = await _tg.getSender(dcId);
const res = await _tg.invokeWithSender(
    new Api.upload.GetFileHashes({
      location: info.location,
    }),
    sender
);
return res;
```
