### ISSUE TITLE
get live messages updates from a channel

### ISSUE THREAD

**Issue by hadifarnoud** [gram-js/gramjs#469]
I need to get new channel messages live and then do something on it. I could not find an example for that. 

can anyone provide an example?

**Comment by painor** [comment]
you can use https://gram.js.org/beta/classes/TelegramClient.html#addEventHandler
https://gram.js.org/beta/classes/custom.NewMessage.html

**Comment by hadifarnoud** [comment]
Thanks for the quick reply. can you please give me an example?

I need messages from a specific channel(s), not all. I also don't know where I can parse the message and do something.

**Comment by painor** [comment]
(the links have example).
you can also just console log and see the attribute etc

**Comment by hadifarnoud** [comment]
the example is typescript and look incomplete. I was not able to  run it at all.
```
ReferenceError: NewMessage is not defined
    at Object.<anonymous> (/Users/hadifarnoud/.config/clash/v2ray_bot/index.js:15:37)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

here is my code
```
const { Api, TelegramClient } = require("telegram");
const { StringSession } = require("telegram/sessions");

const apiId = 27281770;
const apiHash = "****";
const stringSession = new StringSession("******"); // fill this later with the value from session.save()
const client = new TelegramClient(stringSession, apiId, apiHash, {
    connectionRetries: 5,
  });

async function handler(event) {
  await client.connect();
}
client.addEventHandler(handler, new NewMessage({}));

```
