### ISSUE TITLE
Reaction Error

### ISSUE THREAD

**Issue by dandyraka** [gram-js/gramjs#477]
When I try
```ts
const result = await client.invoke(
                    new Api.messages.SendReaction({
                        peer: "username",
                        msgId: 38821,
                        reaction: "👍",
                    })
                );
                console.log(result);`
```
Then show error
```
TypeError: this[arg].map is not a function
    at VirtualClass.getBytes (C:\laragon\www\JKT48PM_STATS\node_modules\telegram\tl\api.js:385:69)
    at new RequestState (C:\laragon\www\JKT48PM_STATS\node_modules\telegram\network\RequestState.js:9:29)
    at MTProtoSender.send (C:\laragon\www\JKT48PM_STATS\node_modules\telegram\network\MTProtoSender.js:203:23)
    at Object.invoke (C:\laragon\www\JKT48PM_STATS\node_modules\telegram\client\users.js:31:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eventPrint (file:///C:/laragon/www/JKT48PM_STATS/index.js:196:32)
    at async _dispatchUpdate (C:\laragon\www\JKT48PM_STATS\node_modules\telegram\client\updates.js:141:21)
```

**Comment by painor** [comment]
The function has changed a while ago. you should now use 
`reaction: [Api.ReactionEmoji({ emoticon: "👍" })]`

**Comment by dandyraka** [comment]
> 

It works, thanks 👍

**Comment by pboethig2** [comment]
reaction: [new Api.ReactionEmoji({ emoticon: emoji })], 
      
      the new keyword was missing
