### ISSUE TITLE
How to accept a secret chat

### ISSUE THREAD

**Issue by dusthijsvdh** [gram-js/gramjs#500]
Hi, I was wondering how to accept a secret chat.
When listening to all raw updates, and someone sends you a secret chat request it looks as follows:
```js
{
  CONSTRUCTOR_ID: 3030575245,
  SUBCLASS_OF_ID: 2676568142,
  className: 'UpdateEncryption',
  classType: 'constructor',
  chat: {
    CONSTRUCTOR_ID: 1223809356,
    SUBCLASS_OF_ID: 1831379834,
    className: 'EncryptedChatRequested',
    classType: 'constructor',
    flags: 0,
    folderId: null,
    id: NEGATIVENUMBER,
    accessHash: Integer { value: BIGINT },
    date: 1678550555,
    adminId: Integer { value: BIGINT },
    participantId: Integer { value: BIGINT},
    gA: BUFFER
  },
  date: 1678550555
}
```
Then according to the [documentation](https://gram.js.org/tl/messages/AcceptEncryption#messagesacceptencryption) My code should look something like this:
```ts
const result = await this.telegramClientService.client.invoke(
  new Api.messages.AcceptEncryption({
    peer: new Api.InputEncryptedChat({
      accessHash: chat.accessHash,
      chatId: chat.id,
    }),
    gB: Buffer.from('some bytes here'),
    keyFingerprint: chat.accessHash,
  }),
);
```
Except this doesn't work and I get the following error which is not listed in possible errors:
```
RPCError: 400: DH_G_B_INVALID (caused by messages.AcceptEncryption)
    at RPCMessageToError (REDACTED\node_modules\telegram\errors\index.js:28:12)
    at MTProtoSender._handleRPCResult (REDACTED\node_modules\telegram\network\MTProtoSender.js:517:58)
    at MTProtoSender._processMessage (REDACTED\node_modules\telegram\network\MTProtoSender.js:442:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (REDACTED\node_modules\telegram\network\MTProtoSender.js:418:17) {
  code: 400,
  errorMessage: 'DH_G_B_INVALID'
}
```

How would I calculate the correct gb value?
I tried to make something work, but that ended with an error that the number was too big.
It looked like this:
```ts
private getGB(dhConfig: Api.messages.TypeDhConfig): bigint {
if (dhConfig.className === 'messages.DhConfigNotModified') {
  throw new Error('Unexpected DhConfigNotModified');
}

const g = BigInt(dhConfig.g);
const p = dhConfig.p.readBigUInt64BE();
const randBytes = randomBytes(16).readBigUInt64BE();

return g ** randBytes % p;
}
```

**Comment by ShifuBadal** [comment]
I am having the same problem right now. Did you find a solution for it?

**Comment by painor** [comment]
accepting it is a lot more complicated. 
A while ago I made a python module that accepts (and chat) with secret chats. 
Maybe you can take a look at it for inspiration. 
https://github.com/painor/telethon-secret-chat

**Comment by dusthijsvdh** [comment]
Thanks! I did look at that already, but I was having trouble figuring out the correct data types. Do you know by chance what type of int the buffers are saved as inside the `dhConfig`?

**Comment by painor** [comment]
you shouldn't try to convert them to other types.
The P value is an Unsigned Big Endian value tho

**Comment by dusthijsvdh** [comment]
Hi, so I've finally had some time to figure this out. I've come a little closer, but I'm still not quite where I want to be.
I can now accept an incoming request for a secret chat, but It automatically closes on itself.

The code looks as follows:
```ts
public async handleNewChat(update: Api.TypeUpdate): Promise<NewChat> {
  update = update as Api.UpdateEncryption;
  this.logger.info('New secret chat requested');
  const chat = update.chat as Api.EncryptedChatRequested;

  if (chat.id === 0) {
    this.logger.warn('Chat has already been accepted');
    throw new Error('Chat has already been accepted');
  }

  const dhConfig = await this.telegramClientService.getDhConfig();
  const b = randomBytes(256).readUInt32BE(0);
  const gA = chat.gA.readUInt32BE(0);
  const p = dhConfig.p.readUInt32BE(0);
  this.checkGA(gA, p);
  const res = this.powmod(gA, b, p);
  const authKey = Buffer.alloc(256);
  authKey.writeUInt32BE(res, 0);

  const keyFingerprint = bigInt(
    struct.unpack('<q', (await sha1(authKey)).subarray(-8))[0].toString(),
  );
  const inputPeer = new Api.InputEncryptedChat({
    chatId: chat.id,
    accessHash: chat.accessHash,
  });

  const gB = this.powmod(dhConfig.g, b, p);
  this.checkGA(gB, p);

  const gBBuffer = Buffer.alloc(256);
  gBBuffer.writeUInt32BE(gB, 0);

  this.logger.info('Accepting secret chat');
  const result = await this.telegramClientService.client.invoke(
    new Api.messages.AcceptEncryption({
      peer: inputPeer,
      gB: gBBuffer,
      keyFingerprint: keyFingerprint,
    }),
  );

  console.log('result of accepting secret chat', result);

  return {
    chat_id: String(chat.id),
    participants: [String(chat.adminId)],
    agent_id: Config.RABBITMQ_APP_ID,
    status: ChatStatus.active,
    timestamp: ~~(Date.now() / 1000),
    metadata: {
      accessHash: chat.accessHash,
      authKey: authKey,
    },
  };
}
```

For the dhconfig:
```ts
public async getDhConfig(): Promise<Api.messages.DhConfig> {
  const dhConfig = await this.client.invoke(
    new Api.messages.GetDhConfig({
      version: 1234,
      randomLength: 0,
    }),
  );

  if (dhConfig instanceof Api.messages.DhConfigNotModified) {
    if (this.dhConfig === undefined) {
      throw new Error('dhConfig is undefined');
    }
    return this.dhConfig;
  } else {
    this.dhConfig = dhConfig;
    return this.dhConfig;
  }
}
```

checkGA
```ts
public checkGA(gA: number, p: number): boolean {
  console.log(gA, p);
  if (gA <= 1 || gA >= p - 1) {
    throw new Error('g_a is invalid (1 < g_a < p - 1 is false).');
  }
  // Ommited, because it just generates infinity as the value to check against
  // if (gA < 2 ** 1984 || gA >= p - 2 ** 1984) {
  //   throw new Error('g_a is invalid (1 < g_a < p - 1 is false).')
  // }

  return true;
}
```

powmod
```ts
private powmod(base: number, exp: number, mod: number): number {
  if (exp === 0) return 1;
  if (exp % 2 === 0) {
    return Math.pow(this.powmod(base, exp / 2, mod), 2) % mod;
  } else {
    return (base * this.powmod(base, exp - 1, mod)) % mod;
  }
}
```

The struct function is from [this library](https://github.com/danielgindi/node-python-struct).
It might not work as it should, but I couldn't figure out that struct part, so I went with this as an alternative.

This almost seems to work, since I get the following as a result:
```js
result of accepting secret chat {
  CONSTRUCTOR_ID: 1643173063,
  SUBCLASS_OF_ID: 1831379834,
  className: 'EncryptedChat',
  classType: 'constructor',
  id: -2000098656,
  accessHash: Integer { value: 5990658173514596959n },
  date: 1680053095,
  adminId: Integer { value: 6144126694n },
  participantId: Integer { value: 989743257n },
  gAOrB: <Buffer 71 22 e9 5a 68 9d 98 67 8d 16 a0 1b 6f a0 bb 61 3a 79 d8 de 29 5e 72 3a 5a b1 40 cd fa f5 a6 28 e8 20 bd f2 6a 87 77 0d e1 f1 81 60 d9 cc 41 e0 1e e3 ... 206 more bytes>,
  keyFingerprint: Integer { value: -4577235981057685008n }
}
```

But after this is done, I immediately get a `EncryptedChatDiscarded` event and the chat is discarded.
Now, the missing piece to this seems to be the [`notify_layer` function](https://github.com/painor/telethon-secret-chat/blob/32e7585ba4f5dbb2c6f025047c11fa52cf55d071/telethon_secret_chat/secret_methods.py#L559).

There is only one problem with implementing this. It seems like I'm missing a message to send to the telegram API. In particular, the [`SendEncryptedServiceRequest`](https://github.com/painor/telethon-secret-chat/blob/32e7585ba4f5dbb2c6f025047c11fa52cf55d071/telethon_secret_chat/secret_methods.py#L567) class.

How would I go about fixing this? Also, could you maybe take a look at this [discussion](https://github.com/gram-js/gramjs/discussions/501)? Right now it's more important to me to figuring out how to decrypt messages than to accept a secret chat.
