### ISSUE TITLE
Resend media message

### ISSUE THREAD

**Issue by LeonidShastel** [gram-js/gramjs#505]
Is it possible to send to another channel all the media in a message that comes from another channel. I put a listener on the channel, if a message with media arrives there, I send them to my messages, not forwarding, but sending on my own behalf.

**Comment by painor** [comment]
you can use client.sendMessage(TargetChannel,event.message)

**Comment by LeonidShastel** [comment]
Yes, I tried that. It works without problems with text messages, but when you try to send a message with any media, such an error takes off. I'm interested in this moment, is there any solution, or just download media, upload it again and make a SendMedia request

`TypeError: Cannot use 'in' operator to search for 'name' in undefined
    at _getExtension (\node_modules\telegram\Utils.js:626:21)
    at _getExtension (\node_modules\telegram\Utils.js:627:16)
    at Object.isImage (\node_modules\telegram\Utils.js:586:17)
    at _fileToMedia (\node_modules\telegram\client\uploads.js:160:35)
    at Object.sendFile (\node_modules\telegram\client\uploads.js:436:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eventPrint (\index.js:69:13)
    at async _dispatchUpdate (\node_modules\telegram\client\updates.js:141:21)`

**Comment by painor** [comment]
what's the actual code you used?

**Comment by LeonidShastel** [comment]
> what's the actual code you used?

```javascript
const getData = async () => {
    for (let i = 0; i<CHANNELS_LISTEN.length; i++){
        try{
            CHANNELS_DATA.listen.push(await client.invoke(
                new Api.channels.GetFullChannel({
                    channel: CHANNELS_LISTEN[i],
                })));
        }
        catch (e) {
            console.error(`Ошибка получение данных канала: ${CHANNELS_LISTEN[i]}`);
        }
    }
    for (let i = 0; i<CHANNELS_POST.length; i++){
        try{
            CHANNELS_DATA.post.push(await client.invoke(
                new Api.channels.GetFullChannel({
                    channel: CHANNELS_POST[i],
                })));
        }
        catch (e) {
            console.error(`Ошибка получение данных канала: ${CHANNELS_POST[i]}`);
        }
    }
};

process.on('SIGHUP', async () => {
    console.log("Программа завершила свою работу");
    await exitFunction();
});
process.on('uncaughtException', async (error) => {
    console.error(`Непредвиденная ошибка: ${error.name}\n${error.message}\n${error.stack}`);
    await exitFunction();
});


(async () => {
    const sessions = getSessions();
    const sessionForGramJS = await sessionsDecoder(sessions[0]);
    client = new TelegramClient(sessionForGramJS.store, sessionForGramJS.appId, sessionForGramJS.appHash, {
        connectionRetries: 50, autoReconnect: true
    });
    client.setLogLevel("info");
    await client.connect();
    const result = await client.getMe();

    console.info(`Получение данных каналов...`);
    await getData();
    console.info(`Получение данных закончено. Запуск аккаунта`);

    client.addEventHandler(eventPrint, new NewMessage({}));
    console.info(`${sessions[0]} started`);
})();
```

**Comment by painor** [comment]
weird, i tested it and it worked for me.
in any case you can use forward message with "dropAuthor = true"

**Comment by LeonidShastel** [comment]
> weird, i tested it and it worked for me.
> 
> in any case you can use forward message with "dropAuthor = true"

There's another question. Is it possible to forward multimedia like that? Such a message is like a few different ones. Somehow combine and forward with dropAuthor
