### ISSUE TITLE
GetDialogs fails with error

### ISSUE THREAD

**Issue by klinki** [gram-js/gramjs#585]
Hi,  I have following code

```typescript
          const dialogs: TotalList<Dialog> = await client.getDialogs({          });
```

and it fails with following error:

> TypeError: Cannot read properties of undefined (reading 'date')
>     at new Dialog (https://deno.land/x/gram@0.8.4/tl/custom/dialog.ts:40:31)
>     at _DialogsIter._loadNextChunk (https://deno.land/x/gram@0.8.4/client/dialogs.ts:139:20)
>     at eventLoopTick (ext:core/01_core.js:183:11)
>     at async Object.next (https://deno.land/x/gram@0.8.4/request_iter.ts:69:29)
>     at async Module.getDialogs (https://deno.land/x/gram@0.8.4/client/dialogs.ts:210:20)
>     at async file:///C:/projects/telegram-bot/main.ts:38:46

It seems message could be null and `this.date = this.message!.date!;` it will fail here in that case.

**Comment by baumschubser** [comment]
Same is happening to me. Seems odd that the possibility of message === undefined is ruled out, here. 

That line is called from [here](https://github.com/gram-js/gramjs/blob/f0081081d1416811fa61334badf0178a7be6dd5c/gramjs/client/dialogs.ts#L159C17-L159C74). message is the dialog's top message and it can be undefined. In that case message.originalMessage is undefined, too, and thats the object that is undefined in the error cited above.
