### ISSUE TITLE
StringSession No more data left to read (need 23404, got 260: ..)

### ISSUE THREAD

**Issue by maheshbansod** [gram-js/gramjs#59]
I've tested the same session string with telethon and it worked. No clue why I'm getting this on gramjs:
```
(node:5682) UnhandledPromiseRejectionWarning: Error: No more data left to read (need 23404, got 260: 8p�o��GAT.�@/��˥�o7Q�ʬ�L�`�v�#<o�E�I�L7
                                                                                                                                            9s��?�����~_גt�o�f��ٱi�N��<�g�$���^���i�D��k�x���4���ʌ�����Hv�b�o>l{�������=
�؛O�ʨ��Խ             �)�§��2O;H��&�
        M����.٬��(�$7); last read [l
    at BinaryReader.read (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/extensions/BinaryReader.js:85:19)
    at new StringSession (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/sessions/StringSession.js:46:49)
    at Object.<anonymous> (/home/zero/apps/epic-light-bot-old/epic-light-bot/gramjs.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/zero/apps/epic-light-bot-old/epic-light-bot/testgram.js:2:23
```

My code is:
```
var string_session = new StringSession(STRING_SESSION);
const client = new TelegramClient(string_session, API_ID, API_HASH);
```

**Comment by painor** [comment]
where did you get the string session from ?

**Comment by maheshbansod** [comment]
I took it using a python script using telethon.

I tried generating it with gramjs (by using the parameter `new StringSession('')` in TelegramClient constructor) but I get this error:
```

(node:6267) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'phoneNumber' in undefined
    at TelegramClient.<anonymous> (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:318:38)
    at Generator.next (<anonymous>)
    at /home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:23:12)
    at TelegramClient.authFlow (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:317:16)
    at TelegramClient.<anonymous> (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:51:24)
    at Generator.next (<anonymous>)
    at fulfilled (/home/zero/apps/epic-light-bot-old/epic-light-bot/node_modules/telegram/dist/client/auth.js:24:58)

```

**Comment by painor** [comment]
probably better to use TS because it's expecting more args for the start()
I might have broke telethon session support on accident. we'll be fixed soon. 
check examples here in the meantime https://github.com/gram-js/gramjs/blob/master/examples/main.ts

**Comment by maheshbansod** [comment]
Okay, thanks. Let me know when it's fixed?

Maybe I'll try and use an older version or switch to typescript for now.

Should I close the issue or you'll when it's done?

**Comment by painor** [comment]
I'll do it myself.

**Comment by painor** [comment]
so the thing is telethon assumes that server address is always in IP form (x.x.x.x) so it doesn't support websocket endpoints that are URLs not IPs for that reason there can't be a 1 to 1 compatibility between the two because gramJS saves those IPs and URLs as strings while telethon packs them. 

For now you can import telethon sessions into gramjs but you can't use gramjs sessions into telethon.
