### ISSUE TITLE
No longer able to connect

### ISSUE THREAD

**Issue by mmaestrini** [gram-js/gramjs#590]
I started using this yesterday and logged in just fine. Stored session  string in db and load it when needing to reconnect. 

I have a script that connects every x minutes to check for new messages, but all of a sudden I am getting these errors:

Error: Not connected
    at ConnectionTCPFull.recv (/bot/node_modules/telegram/network/connection/Connection.js:70:15)
    at MTProtoSender._recvLoop (bot/node_modules/telegram/network/MTProtoSender.js:359:24)
[2023-09-28T12:06:56.067] [INFO] - [Started reconnecting]
[2023-09-28T12:06:56.067] [WARN] - [[Reconnect] Closing current connection...]
[2023-09-28T12:06:56.067] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
[2023-09-28T12:06:56.068] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2023-09-28T12:06:56.664] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2023-09-28T12:06:56.665] [INFO] - [Handling reconnect!]
[2023-09-28T12:07:00.316] [INFO] - [connection closed]
[2023-09-28T12:07:00.317] [WARN] - [Connection closed while receiving data]

What is the issue? are we allowed to connect often to check for new messages or is that an issue? have i been deactivated? I didnt get any more info in the exception i get except those...

**Comment by painor** [comment]
you can remove the console logs using https://gram.js.org/beta/classes/TelegramClient.html#setLogLevel

Are you sure you're not having network issues ?

**Comment by mmaestrini** [comment]
mmmhhh that'd be odd, cause I tried both on my bot running on heroku as well as on my local machine. 

can you confirm if there is any issue with connecting like every 1-5 minutes?

Also once I have the string session, do I need to ever recreate it? I am storing it in my database and load it before I start. 

I am trying the following:

```
const telegramSession = (
      await this.db.getInstance().raw(`SELECT session FROM telegram`)
    ).rows[0]?.session;

    // (async () => {

    try {
      const stringSession = new StringSession(telegramSession); // fill this later with the value from session.save()

      const client = new TelegramClient(stringSession, apiId, apiHash, {
        connectionRetries: 5,
      });
      await client.connect();
      const dialogs = await client.getDialogs({});
      }catch(err){
      console.error(err);
      }
```

Do you see any issues with this?

**Comment by mmaestrini** [comment]
@painor I just noticed #589  seems to be the same as I am experiencing

**Comment by mmaestrini** [comment]
Very odd, now my telegram on my laptop does not have a new message in a group i am in whereas my phone does have that message! Does anyone have an idea what's going on?

**Comment by mmaestrini** [comment]
I tried to do client.setLogLevel(LogLevel.NONE); but it is still logging ... :/

**Comment by v-dev-cl** [comment]
I'm also having this "issue", using current version and prev .17 with a stable net connection, tested on a vps and my local PC

**Comment by mmaestrini** [comment]
Now I am getting AUTH_KEY_DUPLICATED what's going on? anyone? why did it work just fine initially and now doesn't?

**Comment by GoranTopic** [comment]
I am having the same kind of error. For me it actually gets suck in a loop with the error logs:
[2023-10-05T13:45:55.586] [INFO] - [Started reconnecting]                                                                                                                                                                                                                       
[2023-10-05T13:45:55.586] [WARN] - [[Reconnect] Closing current connection...]                                                                                                                                                                                                  
[2023-10-05T13:45:55.586] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...]                                                                                                                                                                                            
[2023-10-05T13:45:55.586] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...]                                                                                                                                                                                                 
[2023-10-05T13:45:55.649] [INFO] - [Started reconnecting]                                                                                                                                                                                                                       
[2023-10-05T13:45:55.649] [WARN] - [[Reconnect] Closing current connection...]                                                                                                                                                                                                  
[2023-10-05T13:45:55.649] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...]                                                                                                                                                                                            
[2023-10-05T13:45:55.649] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...]                                                                                                                                                                                                 
[2023-10-05T13:45:55.684] [INFO] - [Connection to 149.154.175.55:80/TCPFull complete!]                                                                                                                                                                                          
[2023-10-05T13:45:55.684] [INFO] - [Handling reconnect!]                                                                                                                                                                                                                        
[2023-10-05T13:45:55.749] [INFO] - [Connection to 149.154.175.55:80/TCPFull complete!]                                                                                                                                                                                          
[2023-10-05T13:45:55.749] [INFO] - [Handling reconnect!]                                                                                                                                                                                                                        
[2023-10-05T13:45:55.757] [INFO] - [connection closed]                                                                                                                                                                                                                          
[2023-10-05T13:45:55.757] [WARN] - [Connection closed while receiving data]                                                                                                                                                                                                     
Error: Not connected                                                                                                                                                                                                                                                            
    at ConnectionTCPFull.recv (/home/user/telegram_scrap/node_modules/telegram/network/connection/Connection.js:70:15)                                                                                                                                                         
    at async MTProtoSender._recvLoop (/home/user/telegram_scrap/node_modules/telegram/network/MTProtoSender.js:359:24)                                                                                                                                                         
[2023-10-05T13:45:55.826] [INFO] - [connection closed]                                                                                                                                                                                                                          
[2023-10-05T13:45:55.826] [WARN] - [Connection closed while receiving data]                                                                                                                                                                                                     
Error: Not connected                                                                                                                                                                                                                                                            
    at ConnectionTCPFull.recv (/home/user/telegram_scrap/node_modules/telegram/network/connection/Connection.js:70:15)                                                                                                                                                         
    at async MTProtoSender._recvLoop (/home/user/telegram_scrap/node_modules/telegram/network/MTProtoSender.js:359:24)                                                                                                                                                         
[2023-10-05T13:45:56.169] [INFO] - [Started reconnecting]                                                                                                                                                                                                                       
[2023-10-05T13:45:56.169] [WARN] - [[Reconnect] Closing current connection...]                                                                                                                                                                                                  
[2023-10-05T13:45:56.169] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...]                                                                                                                                                                                            
[2023-10-05T13:45:56.169] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...]                                                                                                                                                                                                 
[2023-10-05T13:45:56.296] [INFO] - [Started reconnecting]        

When I restart my script, it seems to run fine again for a while.
It does not throw an Error, So I am unable to handle it programmatically...

**Comment by rahbari** [comment]
same here, now it freeze after this:
<img width="552" alt="image" src="https://github.com/gram-js/gramjs/assets/163890/72026b69-9780-4c84-a68e-7bf562c99900">

**Comment by v-dev-cl** [comment]
> guys, if someone will find a solution, text here, please

not a solution but I've been running a service without issues in functionality even with the disconnect messages, besides i'm using a health check testing the connection and k8s automatically restart the pod if the connection is not working.

```
// telegram.service.ts

isConnected = async (): Promise<boolean> => {
    try {
      const callConfig = await this.getCallConfig(); // It can be any method that requires connection
      return !!(callConfig && callConfig.data);
    } catch (err) {
      this.logger.error(`Error ${err.message}`);
    }

    return false;
  };
```
 

```
// health.service.ts

async isTelegramClientHealthy(): Promise<boolean> {
    const isConnected = await this.telegramService.isConnected();

    if (!isConnected) {
      this.logger.error(`Telegram client service is not connected`);
      const result = this.getStatus(HealthEnum.TELEGRAM_CLIENT, null);
      throw new HealthCheckError(HealthEnum.TELEGRAM_CLIENT + ' failed', result);
    }

    return isConnected;
  }
```

**Comment by v-dev-cl** [comment]
I just read the logs of my service and there aren't more disconnect messages (no code changes), so it could have been something from Telegram side

**Comment by prakashgp** [comment]
connectionRetries just never works for me, It is stuck in infinite retries. 
I am using a SOCKS5 proxy - that might be the reason

**Comment by NarHakobyan** [comment]
Has anyone fixed this?

**Comment by maxktz** [comment]
> I am having the same kind of error. For me it actually gets suck in a loop with the error logs: [2023-10-05T13:45:55.586] [INFO] - [Started reconnecting] [2023-10-05T13:45:55.586] [WARN] - [[Reconnect] Closing current connection...] [2023-10-05T13:45:55.586] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:55.586] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:55.649] [INFO] - [Started reconnecting] [2023-10-05T13:45:55.649] [WARN] - [[Reconnect] Closing current connection...] [2023-10-05T13:45:55.649] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:55.649] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:55.684] [INFO] - [Connection to 149.154.175.55:80/TCPFull complete!] [2023-10-05T13:45:55.684] [INFO] - [Handling reconnect!] [2023-10-05T13:45:55.749] [INFO] - [Connection to 149.154.175.55:80/TCPFull complete!] [2023-10-05T13:45:55.749] [INFO] - [Handling reconnect!] [2023-10-05T13:45:55.757] [INFO] - [connection closed] [2023-10-05T13:45:55.757] [WARN] - [Connection closed while receiving data] Error: Not connected at ConnectionTCPFull.recv (/home/user/telegram_scrap/node_modules/telegram/network/connection/Connection.js:70:15) at async MTProtoSender._recvLoop (/home/user/telegram_scrap/node_modules/telegram/network/MTProtoSender.js:359:24) [2023-10-05T13:45:55.826] [INFO] - [connection closed] [2023-10-05T13:45:55.826] [WARN] - [Connection closed while receiving data] Error: Not connected at ConnectionTCPFull.recv (/home/user/telegram_scrap/node_modules/telegram/network/connection/Connection.js:70:15) at async MTProtoSender._recvLoop (/home/user/telegram_scrap/node_modules/telegram/network/MTProtoSender.js:359:24) [2023-10-05T13:45:56.169] [INFO] - [Started reconnecting] [2023-10-05T13:45:56.169] [WARN] - [[Reconnect] Closing current connection...] [2023-10-05T13:45:56.169] [INFO] - [Disconnecting from 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:56.169] [INFO] - [Connecting to 149.154.175.55:80/TCPFull...] [2023-10-05T13:45:56.296] [INFO] - [Started reconnecting]
> 
> When I restart my script, it seems to run fine again for a while. It does not throw an Error, So I am unable to handle it programmatically...

Just facing this, have you fixed man?
