### ISSUE TITLE
Client.disconnect() has been executed, but _updateLoop not fully uninstalled

### ISSUE THREAD

**Issue by kaadon** [gram-js/gramjs#615]
```shell 
[2023-11-29T10:52:12.165] [INFO] - [Running gramJS version 2.19.9]
[2023-11-29T10:52:12.167] [INFO] - [Connecting to 91.108.56.133:80/TCPFull...]
[2023-11-29T10:52:12.293] [INFO] - [Connection to 91.108.56.133:80/TCPFull complete!]
[2023-11-29T10:52:12.294] [INFO] - [Using LAYER 166 for initial connect]
[2023-11-29T10:52:15.640] [WARN] - [Disconnecting...]
[2023-11-29T10:52:15.640] [INFO] - [Disconnecting from 91.108.56.133:80/TCPFull...]
[2023-11-29T10:52:15.642] [INFO] - [connection closed]

Error: TIMEOUT
    at /Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:244:85
    at async attempts (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:228:20)
    at async _updateLoop (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:180:17)

Error: TIMEOUT
    at /Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:244:85
    at async attempts (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:228:20)
    at async _updateLoop (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:180:17)

Error: TIMEOUT
    at /Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:244:85
    at async attempts (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:228:20)
    at async _updateLoop (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:180:17)

Error: TIMEOUT
    at /Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:244:85
    at async attempts (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:228:20)
    at async _updateLoop (/Volumes/SourceData/webhook/node/telegram_protocol_number/node_modules/telegram/client/updates.js:180:17)
```

**Comment by davie-robertson** [comment]
I'm also getting this in 2.19.10 - I didn't see this before on previous versions

**Comment by andrezero0** [comment]
conseguirão achar uma solução

**Comment by davie-robertson** [comment]
I've started using ` await client.destroy();` instead of disconnect - not sure if this is going to cause me a problem long term, but it gets rid of this issue/bug

**Comment by andrezero0** [comment]
na 2.19.10

**Comment by SergeyTverye** [comment]
> I've started using ` await client.destroy();` instead of disconnect - not sure if this is going to cause me a problem long term, but it gets rid of this issue/bug

Finally got rid of this timeout spam in the console. Thank you! Works great for me. I make a disconnect and then client destroy.
```
            await this.client.disconnect();
            await this.client.destroy();
```
