### ISSUE TITLE
PEER_ID_INVALID and business bot

### ISSUE THREAD

**Issue by alexey-sh** [gram-js/gramjs#700]
I have Premium Telegram account and created Business Telegram bot. So it is able to receive notifications from all my chats, but when I try to send message, it throws the following error
```
Fail RPCError: 400: PEER_ID_INVALID (caused by InvokeWithBusinessConnection)
    at RPCMessageToError (/Users/alexeysh/dev/tg-api-no-bot/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/Users/alexeysh/dev/tg-api-no-bot/node_modules/telegram/network/MTProtoSender.js:546:58)
    at MTProtoSender._processMessage (/Users/alexeysh/dev/tg-api-no-bot/node_modules/telegram/network/MTProtoSender.js:476:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/Users/alexeysh/dev/tg-api-no-bot/node_modules/telegram/network/MTProtoSender.js:424:17) {
  code: 400,
  errorMessage: 'PEER_ID_INVALID'
}
```

this is my code

```
   console.log('started', await client.start({
        botAuthToken: BOT_TOKEN,
    }));

    client.addEventHandler(async (update: Api.TypeUpdate) => {
        if (update instanceof UpdateBotNewBusinessMessage) {
            try {
                const result = await client.invoke(new Api.InvokeWithBusinessConnection ({
                    connectionId: update.connectionId,
                    query: new Api.messages.SendMessage({
                        // @ts-ignore
                        peer: update.message.fromId,
                        message: "Hello there!",
                        // @ts-ignore
                        // sendAs: update.message.peerId, // does not help
                    })
                }));
                console.log('ok', result);
            } catch (e) {
                console.error('Fail', e);
            }
        }
    });
```

>Business users can connect Telegram bots that will process and answer messages on their behalf. This allows businesses to seamlessly integrate any existing tools and workflows, or add AI assistants that manage their chats.

The documentation says it is possible, but it seems not to be.

**Comment by sergey87028471772** [comment]
Hi man, did you find someway to fix it? I need change message in 1-1 chat in business mode, I know about invokeWithBusinessConnection, but I can't call it in js context.

**Comment by vlad1slove1** [comment]
@alexey-sh, @sergey87028471772 good day! Seems i've found solution for business bot to reply on incoming messages with gramjs:
```ts
private async handleMessage(): Promise<void> {
        this.client.addEventHandler(async (update) => {
            if (update instanceof Api.UpdateBotNewBusinessMessage) {
                try {
                    const { connectionId, message } = update;

                    const inputPeer: Api.TypeInputPeer = await this.client.getInputEntity(
                        message.peerId as Api.TypeEntityLike
                    );

                    await this.client.invoke(
                        new Api.InvokeWithBusinessConnection({
                            connectionId,
                            query: new Api.messages.SendMessage({
                                peer: inputPeer,
                                message: 'Hello from business-bot!',
                                randomId: generateRandomBigInt(),
                            }),
                        })
                    );
                } catch (err) {
                    console.error('Failed to send message:', err);
                }
            }
        });
    }
```

The problem was to get correct **inputPeer** type and pass it into **Api.messages.SendMessage** props

https://github.com/user-attachments/assets/ca2acbe1-ff4d-496c-a56e-ac5e71e086f7

**Comment by alexey-sh** [comment]
@sergey87028471772
I found a way but I don't remember details. Perhaps it was like the solution provided by @vlad1slove1.
