### ISSUE TITLE
how i can click reply markun button and get the response?

### ISSUE THREAD

**Issue by zarlicho** [gram-js/gramjs#705]
i have trying button.click like this 
`client.addEventHandler(async (event) => {
    if (event.message.buttons != undefined){
      console.log(event.message.buttons[1][0].click())
    }`
    
   and i got this error:
   
   `Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'sharePhone')
      at MessageButton.click (F:\pythonProject\myProject\client dexter\telbot\node_modules\telegram\tl\custom\messageButton.js:70:19)
      at F:\pythonProject\myProject\client dexter\telbot\test.js:36:47
      at _dispatchUpdate (F:\pythonProject\myProject\client dexter\telbot\node_modules\telegram\client\updates.js:144:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
F:\pythonProject\myProject\client dexter\telbot\node_modules\telegram\tl\custom\messageButton.js:70
    async click({ sharePhone = false, shareGeo = [0, 0], password, }) {
                  ^

TypeError: Cannot read properties of undefined (reading 'sharePhone')
    at MessageButton.click (F:\pythonProject\myProject\client dexter\telbot\node_modules\telegram\tl\custom\messageButton.js:70:19)
    at F:\pythonProject\myProject\client dexter\telbot\test.js:36:47
    at _dispatchUpdate (F:\pythonProject\myProject\client dexter\telbot\node_modules\telegram\client\updates.js:144:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0`

**Comment by painor** [comment]
try .click({})

**Comment by MJBlack9000** [comment]
You might need to get the callback data from the button, and then just directly send that data to the bot.
For example, if the button's callback data would be "main_menu_button_data", you'd need to send it like so:
```
const result = await client.invoke(
    new Api.messages.GetBotCallbackAnswer({
      peer: "username",
      msgId: 43,
      game: true,
      data: Buffer.from("main_menu_button_data"),
    })
  );
  ```
I've not ran this command myself, so I don't know if it will work. But I found it in the docs, and it seems like exactly what you'd need to do: https://gram.js.org/tl/messages/GetBotCallbackAnswer
