### ISSUE TITLE
RPCError: 400: USERNAME_INVALID (caused by contacts.ResolveUsername)

### ISSUE THREAD

**Issue by tocha688** [gram-js/gramjs#748]
```
C:\Codes\tdl-test\node_modules\.pnpm\telegram@2.26.6\node_modules\telegram\errors\index.js:28
    return new RPCBaseErrors_1.RPCError(rpcError.errorMessage, request, rpcError.errorCode);
           ^

RPCError: 400: USERNAME_INVALID (caused by contacts.ResolveUsername)
    at RPCMessageToError (C:\Codes\tdl-test\node_modules\.pnpm\telegram@2.26.6\node_modules\telegram\errors\index.js:28:12)
    at MTProtoSender._handleRPCResult (C:\Codes\tdl-test\node_modules\.pnpm\telegram@2.26.6\node_modules\telegram\network\MTProtoSender.js:561:58)
    at MTProtoSender._processMessage (C:\Codes\tdl-test\node_modules\.pnpm\telegram@2.26.6\node_modules\telegram\network\MTProtoSender.js:492:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (C:\Codes\tdl-test\node_modules\.pnpm\telegram@2.26.6\node_modules\telegram\network\MTProtoSender.js:439:17) {
  code: 400,
  errorMessage: 'USERNAME_INVALID'
}
```

**Comment by alexsahka** [comment]
I have the same issue: RPCError: 400: USERNAME_INVALID (caused by contacts.ResolveUsername)
It worked for 1 day then started getting this error.

Could you let me know if you resolved this problem?
