### ISSUE TITLE
BOT_METHOD_INVALID: Can't use client.getMessages with bot

### ISSUE THREAD

**Issue by jsjoeio** [gram-js/gramjs#76]
I'm trying to get messages from a group using `client.getMessages` and a bot.

I have a Telegram group with three people: myself, a friend and a bot.

I changed the privacy settings for the bot and I made the bot an admin in the group:

![image](https://user-images.githubusercontent.com/3806031/117848876-943efa00-b238-11eb-8d92-fa75d3eadb2d.png)

![image](https://user-images.githubusercontent.com/3806031/117848936-aae55100-b238-11eb-85ae-af69a7652541.png)

```javascript
const { TelegramClient } = require("telegram")
const { StringSession } = require("telegram/sessions")

const stringSession = ""
const apiId = <redacted>
const apiHash = "<redacted>"
const groupId = <redacted>
const BOT_TOKEN = "<redacted" // put your bot token here
;(async () => {
  const client = new TelegramClient(
    new StringSession(stringSession),
    apiId,
    apiHash,
    { connectionRetries: 5 }
  )
  await client.start({
    botAuthToken: BOT_TOKEN,
  })
  console.log(client.session.save())

  const msgs = await client.getMessages(groupId, {
    limit: 2,
  })
  // this works
  // await client.sendMessage(groupId, { message: "hello there" })
  console.log("the total number of msgs are", msgs.total)
  console.log("what we got is ", msgs.length)
  for (const msg of msgs) {
    console.log("msg is", msg) // this line is very verbose but helpful for debugging
    console.log("msg text is : ", msg.text)
  }
})()
```

Stack trace:
```javascript
(node:14525) UnhandledPromiseRejectionWarning: Error: BOT_METHOD_INVALID
    at Object.RPCMessageToError (/Users/jp/Dev/pag-messages/node_modules/telegram/errors/index.js:24:12)
    at MTProtoSender._handleRPCResult (/Users/jp/Dev/pag-messages/node_modules/telegram/network/MTProtoSender.js:491:36)
    at MTProtoSender.<anonymous> (/Users/jp/Dev/pag-messages/node_modules/telegram/network/MTProtoSender.js:415:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jp/Dev/pag-messages/node_modules/telegram/network/MTProtoSender.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What am I doing wrong? Any help is appreciated! Thank you ♥️

**Comment by painor** [comment]
it's not possible for bots to iterate overs message history the way users do. 
you can only get a message if you know its ID. it's probably a better idea to use events when using bot accounts instead of `getMessages `anyways.
