### ISSUE TITLE
importContacts not working

### ISSUE THREAD

**Issue by kungfu321** [gram-js/gramjs#81]
I try importContacts but it's not working
This is my code

```
import {Api, TelegramClient} from 'telegram';
import { StringSession } from 'telegram/sessions';

const stringSession = '';
const BOT_TOKEN = '';
const apiId = '';
const apiHash = '';

const session = new StringSession(stringSession);

const client = new TelegramClient(session, apiId, apiHash, {});

export default async (req, res) => {
  const result = await client.invoke(
    new Api.contacts.importContacts({
      contacts: [
        new Api.InputContact({
          phone_number: '+888xxxx',
          first_name: 'mob12',
          last_name: 'mob12',
          client_id: 0
        }),
      ],
    }),
  );
  console.log(result);
  res.status(200).json({ success: true })
}

```

Then error code

```
TypeError: telegram__WEBPACK_IMPORTED_MODULE_0__.Api.InputContact is not a constructor
    at __webpack_exports__.default (webpack-internal:///./pages/api/hello.js:18:16)
    at apiResolver (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async DevServer.handleApiRequest (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/vomanhkien/dev/test/gram-bot/node_modules/next/dist/next-server/server/next-server.js:32:504)
```

**Comment by painor** [comment]
try using `ImportContacts` instead of `importContacts `(all functions are CamelCase). 
The params are camelCase so it's phoneNumber not phone_number.
`clientId `should be a random number not 0.
use `Api.InputPhoneContact` instead of `InputContact`

**Comment by kungfu321** [comment]
I did edit follow you're suggested @painor 
Here is my code

```
export default async (req, res) => {
  const result = await client.invoke(
    new Api.contacts.ImportContacts({
      contacts: [
        new Api.InputPhoneContact({
          phoneNumber: '+888xxxx',
          firstName: 'mob12',
          lastName: 'mob12',
          clientId: 23
        }),
      ],
    }),
  );
  console.log(result);
  res.status(200).json({ success: true })
}
```

But I get a new error

```
TypeError: Cannot read property 'send' of undefined
    at Object.<anonymous> (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/client/users.js:41:48)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/client/users.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by kungfu321** [comment]
I forget. I did update my code @painor 

```
export default async (req, res) => {
  await client.connect();
  const result = await client.invoke(
    new Api.contacts.ImportContacts({
      contacts: [
        new Api.InputPhoneContact({
          phone: '+84899911567',
          firstName: 'mob12',
          lastName: 'mob12',
          clientId: 23
        }),
      ],
    }),
  );
  console.log(result);
  res.status(200).json({ success: true })
}
```

And have new an error
```
RPCError: BOT_METHOD_INVALID
    at Object.RPCMessageToError (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/errors/index.js:24:12)
    at MTProtoSender._handleRPCResult (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/network/MTProtoSender.js:488:36)
    at MTProtoSender.<anonymous> (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/network/MTProtoSender.js:412:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vomanhkien/dev/test/gram-bot/node_modules/telegram/network/MTProtoSender.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  code: undefined
}
```

I log in with BOT TOKEN
```
import { TelegramClient } from 'telegram';
import { StringSession } from 'telegram/sessions';

const stringSession = ''; // leave this empty for now
const BOT_TOKEN = ''; // put your bot token here

(async () => {
    const client = new TelegramClient(
        new StringSession(stringSession),
        apiId,
        apiHash,
        { connectionRetries: 5 },
    );
    await client.start({
        botAuthToken: BOT_TOKEN,
    });
    console.log(client.session.save());
})();
```

**Comment by kungfu321** [comment]
It works thanks
