### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range

### ISSUE THREAD

**Issue by mmfKupl** [gram-js/gramjs#82]
Hello

I try to get channel info by `Api.channels.GetFullChannel`.

But when I try to invoke this method
```
const channelInfo = await client.invoke(new Api.channels.GetFullChannel({
      channel: new Api.InputChannel({
        channelId: `-100${id}`,
        accessHash: accessHash,
      }),
    }))
```

I get an error

```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received -1_001_187_737_793
    at checkInt (internal/buffer.js:69:11)
    at writeU_Int32LE (internal/buffer.js:689:3)
    at Buffer.writeInt32LE (internal/buffer.js:858:10)
    at argToBytes (/home/administrator/Desktop/telegramtest/node_modules/telegram/tl/api.js:99:15)
    at VirtualClass.getBytes (/home/administrator/Desktop/telegramtest/node_modules/telegram/tl/api.js:378:42)
    at argToBytes (/home/administrator/Desktop/telegramtest/node_modules/telegram/tl/api.js:122:22)
    at VirtualClass.getBytes (/home/administrator/Desktop/telegramtest/node_modules/telegram/tl/api.js:378:42)
    at new RequestState (/home/administrator/Desktop/telegramtest/node_modules/telegram/network/RequestState.js:9:29)
    at MTProtoSender.send (/home/administrator/Desktop/telegramtest/node_modules/telegram/network/MTProtoSender.js:201:23)
    at Object.<anonymous> (/home/administrator/Desktop/telegramtest/node_modules/telegram/client/users.js:41:48) {
  code: 'ERR_OUT_OF_RANGE'
}
```

I got the right channelId and accessHash for sure

**Comment by painor** [comment]
ids are int. also why are you adding -100 ? just pass the id directly. 
```

const channelInfo = await client.invoke(new Api.channels.GetFullChannel({
      channel: new Api.InputChannel({
        channelId: id,
        accessHash: accessHash,
      }),
    }))

```

**Comment by painor** [comment]
the access hash is most likely wrong. they should be big ints so they would have more digits than that. how did u get it ?

**Comment by mmfKupl** [comment]
you right!
I use this code
```
await client.invoke(new Api.contacts.ResolveUsername({
  username: 'hack_pro_dota',
}));
```

but use CONSTRUCTOR_ID instead of accessHash -_-

thanks for the prompt help!
