### ISSUE TITLE
Uploaded media files doesn`t downloading 

### ISSUE THREAD

**Issue by MotionForward** [gram-js/gramjs#92]
Hi,
I`m trying to download media files from channel messages, but if files were uploaded by me from computer it throws error:
Error: Could not create sender for DC 2
For example, if gif were added from ui telegram - its works fine, but if the same gif added from PC - throwing error for some reason.
How can I fix this?

```async function getHistory() {
  const client = new TelegramClient(session, api_id, api_hash, {});
  await client.start();
  const result = await client.invoke(new Api.messages.GetHistory({
    peer: 'myChannel',
    limit: 10,
  }));
  for (const msg of result.messages) {
    if (msg.media) {
      const buffer = await client.downloadMedia(msg.media, {
        workers: 1,
        dcId: 2
      });
      console.log(buffer)
    }
  }
};

**Comment by BLUE-DEVIL1134** [comment]
Can you show the exact error?

**Comment by MotionForward** [comment]
```
(node:1688) UnhandledPromiseRejectionWarning: Error: Could not create sender for DC 2
    at TelegramClient.<anonymous> (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:299:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1688) UnhandledPromiseRejectionWarning: Error: Could not create sender for DC 2
    at TelegramClient.<anonymous> (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:299:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by MotionForward** [comment]
there is full logs
```
[2021-06-03T09:41:12.711Z] [DEBUG] - [Running gramJS version 1.5.27]
[2021-06-03T09:41:12.718Z] [INFO] - [Connecting to 149.154.167.51:80/TCPFull...]
[2021-06-03T09:41:12.718Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:12.758Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:12.760Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:12.774Z] [DEBUG] - [Already have an auth key ...]
[2021-06-03T09:41:12.775Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:12.775Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:12.776Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:12.776Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:12.777Z] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!]
[2021-06-03T09:41:12.780Z] [DEBUG] - [Assigned msgId = 6969500437141152684 to InvokeWithLayer]
[2021-06-03T09:41:12.780Z] [DEBUG] - [Encrypting 1 message(s) in 80 bytes for sending]
[2021-06-03T09:41:12.784Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:12.784Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:12.827Z] [DEBUG] - [Handling bad salt for message 6969500437141152684]
[2021-06-03T09:41:12.827Z] [DEBUG] - [1 message(s) will be resent]
[2021-06-03T09:41:12.828Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:12.828Z] [DEBUG] - [Assigned msgId = 6969500437337152784 to InvokeWithLayer]
[2021-06-03T09:41:12.828Z] [DEBUG] - [Encrypting 1 message(s) in 80 bytes for sending]
[2021-06-03T09:41:12.830Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:12.830Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:12.831Z] [DEBUG] - [Assigned msgId = 6969500437345152204 to MsgsAck]
[2021-06-03T09:41:12.831Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:12.832Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:12.832Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:12.870Z] [DEBUG] - [Handling container]
[2021-06-03T09:41:12.871Z] [DEBUG] - [Handling new session created]
[2021-06-03T09:41:12.871Z] [DEBUG] - [Handling acknowledge for 6969500437337152784]
[2021-06-03T09:41:12.871Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:12.887Z] [DEBUG] - [Handling RPC result for message 6969500437337152784]
[2021-06-03T09:41:12.891Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:12.891Z] [DEBUG] - [Assigned msgId = 6969500437589152640 to updates.GetState]
[2021-06-03T09:41:12.892Z] [DEBUG] - [Encrypting 1 message(s) in 20 bytes for sending]
[2021-06-03T09:41:12.893Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:12.894Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:12.894Z] [DEBUG] - [Assigned msgId = 6969500437601152724 to MsgsAck]
[2021-06-03T09:41:12.894Z] [DEBUG] - [Encrypting 1 message(s) in 60 bytes for sending]
[2021-06-03T09:41:12.895Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:12.895Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.008Z] [DEBUG] - [Handling RPC result for message 6969500437589152640]
[2021-06-03T09:41:13.009Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:13.014Z] [DEBUG] - [Assigned msgId = 6969500438376119560 to messages.SendMessage]
[2021-06-03T09:41:13.015Z] [DEBUG] - [Encrypting 1 message(s) in 52 bytes for sending]
[2021-06-03T09:41:13.017Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.018Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.018Z] [DEBUG] - [Assigned msgId = 6969500438392119356 to MsgsAck]
[2021-06-03T09:41:13.019Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:13.021Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.021Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.078Z] [DEBUG] - [Handling RPC result for message 6969500438376119560]
[2021-06-03T09:41:13.081Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:13.083Z] [DEBUG] - [Assigned msgId = 6969500438652119584 to contacts.ResolveUsername]
[2021-06-03T09:41:13.084Z] [DEBUG] - [Encrypting 1 message(s) in 32 bytes for sending]
[2021-06-03T09:41:13.085Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.085Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.085Z] [DEBUG] - [Assigned msgId = 6969500438660119960 to MsgsAck]
[2021-06-03T09:41:13.086Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:13.087Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.087Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.218Z] [DEBUG] - [Handling RPC result for message 6969500438652119584]
[2021-06-03T09:41:13.220Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:13.222Z] [DEBUG] - [Assigned msgId = 6969500439204119632 to messages.GetHistory]
[2021-06-03T09:41:13.223Z] [DEBUG] - [Encrypting 1 message(s) in 64 bytes for sending]
[2021-06-03T09:41:13.254Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.254Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.255Z] [DEBUG] - [Assigned msgId = 6969500439336119600 to MsgsAck]
[2021-06-03T09:41:13.255Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:13.256Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.256Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.450Z] [DEBUG] - [Handling RPC result for message 6969500439204119632]
[2021-06-03T09:41:13.463Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:13.468Z] [DEBUG] - [Assigned msgId = 6969500440176119752 to help.GetConfig]
[2021-06-03T09:41:13.468Z] [DEBUG] - [Encrypting 1 message(s) in 20 bytes for sending]
[2021-06-03T09:41:13.470Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.470Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.471Z] [DEBUG] - [Assigned msgId = 6969500440204119632 to MsgsAck]
[2021-06-03T09:41:13.471Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:13.473Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:13.473Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:13.524Z] [DEBUG] - [Handling RPC result for message 6969500440176119752]
[2021-06-03T09:41:13.525Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:13.525Z] [INFO] - [Connecting to 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:13.525Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:13.561Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:13.561Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:13.562Z] [DEBUG] - [New auth_key attempt ...]
[2021-06-03T09:41:13.601Z] [DEBUG] - [Starting authKey generation step 1]
[2021-06-03T09:41:13.601Z] [DEBUG] - [Finished authKey generation step 1]
[2021-06-03T09:41:13.601Z] [DEBUG] - [Starting authKey generation step 2]
[2021-06-03T09:41:13.885Z] [DEBUG] - [Finished authKey generation step 2]
[2021-06-03T09:41:13.886Z] [DEBUG] - [Starting authKey generation step 3]
[2021-06-03T09:41:14.275Z] [DEBUG] - [Finished authKey generation step 3]
[2021-06-03T09:41:14.276Z] [DEBUG] - [Generated new auth_key successfully]
[2021-06-03T09:41:14.276Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:14.277Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.277Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:14.277Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.278Z] [INFO] - [Connection to 149.154.167.51:443/TCPFull complete!]
[2021-06-03T09:41:14.278Z] [INFO] - [Exporting authorization for data center 149.154.167.51]
[2021-06-03T09:41:14.279Z] [DEBUG] - [Assigned msgId = 6969500443731087276 to auth.ExportAuthorization]
[2021-06-03T09:41:14.281Z] [DEBUG] - [Encrypting 1 message(s) in 24 bytes for sending]
[2021-06-03T09:41:14.283Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.284Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.307Z] [DEBUG] - [Assigned msgId = 6969500443843086788 to MsgsAck]
[2021-06-03T09:41:14.308Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.308Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.308Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.329Z] [DEBUG] - [Handling RPC result for message 6969500443731087276]
[2021-06-03T09:41:14.331Z] [INFO] - [Disconnecting from 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.331Z] [DEBUG] - [Closing current connection...]
[2021-06-03T09:41:14.332Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.332Z] [DEBUG] - [Assigned msgId = 6969500443939087460 to MsgsAck]
[2021-06-03T09:41:14.332Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.333Z] [WARN] - [Connection closed while receiving data]
[2021-06-03T09:41:14.334Z] [INFO] - [Connecting to 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.334Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:14.334Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.335Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.335Z] [DEBUG] - [Assigned msgId = 6969500443955087256 to MsgsAck]
[2021-06-03T09:41:14.335Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.339Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.339Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.340Z] [INFO] - [connection closed]
[2021-06-03T09:41:14.377Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:14.377Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:14.378Z] [DEBUG] - [Already have an auth key ...]
[2021-06-03T09:41:14.378Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:14.378Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.378Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:14.378Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.378Z] [INFO] - [Connection to 149.154.167.51:443/TCPFull complete!]
[2021-06-03T09:41:14.379Z] [INFO] - [Exporting authorization for data center 149.154.167.51]
[2021-06-03T09:41:14.379Z] [DEBUG] - [Assigned msgId = 6969500444131086896 to auth.ExportAuthorization]
[2021-06-03T09:41:14.379Z] [DEBUG] - [Encrypting 1 message(s) in 24 bytes for sending]
[2021-06-03T09:41:14.380Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.380Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.471Z] [DEBUG] - [Handling RPC result for message 6969500444131086896]
[2021-06-03T09:41:14.472Z] [INFO] - [Disconnecting from 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.472Z] [DEBUG] - [Closing current connection...]
[2021-06-03T09:41:14.472Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.473Z] [DEBUG] - [Assigned msgId = 6969500444499086928 to MsgsAck]
[2021-06-03T09:41:14.473Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.474Z] [WARN] - [Connection closed while receiving data]
[2021-06-03T09:41:14.475Z] [INFO] - [Connecting to 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.475Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:14.476Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.476Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.477Z] [DEBUG] - [Assigned msgId = 6969500444523087096 to MsgsAck]
[2021-06-03T09:41:14.477Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.479Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.479Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.480Z] [INFO] - [connection closed]
[2021-06-03T09:41:14.516Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:14.517Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:14.517Z] [DEBUG] - [Already have an auth key ...]
[2021-06-03T09:41:14.517Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:14.517Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.518Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:14.518Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.518Z] [INFO] - [Connection to 149.154.167.51:443/TCPFull complete!]
[2021-06-03T09:41:14.518Z] [INFO] - [Exporting authorization for data center 149.154.167.51]
[2021-06-03T09:41:14.519Z] [DEBUG] - [Assigned msgId = 6969500444687086652 to auth.ExportAuthorization]
[2021-06-03T09:41:14.519Z] [DEBUG] - [Encrypting 1 message(s) in 24 bytes for sending]
[2021-06-03T09:41:14.520Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.520Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.604Z] [DEBUG] - [Handling RPC result for message 6969500444687086652]
[2021-06-03T09:41:14.604Z] [INFO] - [Disconnecting from 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.604Z] [DEBUG] - [Closing current connection...]
[2021-06-03T09:41:14.605Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.605Z] [DEBUG] - [Assigned msgId = 6969500445031087468 to MsgsAck]
[2021-06-03T09:41:14.605Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.606Z] [WARN] - [Connection closed while receiving data]
[2021-06-03T09:41:14.606Z] [INFO] - [Connecting to 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.606Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:14.607Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.607Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.608Z] [DEBUG] - [Assigned msgId = 6969500445043087552 to MsgsAck]
[2021-06-03T09:41:14.608Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.609Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.609Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.609Z] [INFO] - [connection closed]
[2021-06-03T09:41:14.654Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Already have an auth key ...]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:14.655Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.655Z] [INFO] - [Connection to 149.154.167.51:443/TCPFull complete!]
[2021-06-03T09:41:14.656Z] [INFO] - [Exporting authorization for data center 149.154.167.51]
[2021-06-03T09:41:14.656Z] [DEBUG] - [Assigned msgId = 6969500445239086696 to auth.ExportAuthorization]
[2021-06-03T09:41:14.656Z] [DEBUG] - [Encrypting 1 message(s) in 24 bytes for sending]
[2021-06-03T09:41:14.657Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.657Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.755Z] [DEBUG] - [Handling RPC result for message 6969500445239086696]
[2021-06-03T09:41:14.757Z] [INFO] - [Disconnecting from 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.757Z] [DEBUG] - [Closing current connection...]
[2021-06-03T09:41:14.757Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.758Z] [DEBUG] - [Assigned msgId = 6969500445639087268 to MsgsAck]
[2021-06-03T09:41:14.758Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.759Z] [WARN] - [Connection closed while receiving data]
[2021-06-03T09:41:14.760Z] [INFO] - [Connecting to 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.760Z] [DEBUG] - [Connecting]
[2021-06-03T09:41:14.761Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.762Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.762Z] [DEBUG] - [Assigned msgId = 6969500445663087436 to MsgsAck]
[2021-06-03T09:41:14.763Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.764Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.764Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.765Z] [INFO] - [connection closed]
[2021-06-03T09:41:14.806Z] [DEBUG] - [Finished connecting]
[2021-06-03T09:41:14.807Z] [DEBUG] - [Connection success!]
[2021-06-03T09:41:14.807Z] [DEBUG] - [Already have an auth key ...]
[2021-06-03T09:41:14.808Z] [DEBUG] - [Starting receive loop]
[2021-06-03T09:41:14.808Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.808Z] [DEBUG] - [Starting send loop]
[2021-06-03T09:41:14.809Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.809Z] [INFO] - [Connection to 149.154.167.51:443/TCPFull complete!]
[2021-06-03T09:41:14.809Z] [INFO] - [Exporting authorization for data center 149.154.167.51]
[2021-06-03T09:41:14.810Z] [DEBUG] - [Assigned msgId = 6969500445855086872 to auth.ExportAuthorization]
[2021-06-03T09:41:14.810Z] [DEBUG] - [Encrypting 1 message(s) in 24 bytes for sending]
[2021-06-03T09:41:14.811Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.811Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.893Z] [DEBUG] - [Handling RPC result for message 6969500445855086872]
[2021-06-03T09:41:14.894Z] [INFO] - [Disconnecting from 149.154.167.51:443/TCPFull...]
[2021-06-03T09:41:14.894Z] [DEBUG] - [Closing current connection...]
[2021-06-03T09:41:14.894Z] [DEBUG] - [Receiving items from the network...]
[2021-06-03T09:41:14.895Z] [DEBUG] - [Assigned msgId = 6969500446191087316 to MsgsAck]
[2021-06-03T09:41:14.895Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.896Z] [WARN] - [Connection closed while receiving data]
[2021-06-03T09:41:14.896Z] [ERROR] - [Error: Could not create sender for DC 2]
[2021-06-03T09:41:14.897Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.897Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-03T09:41:14.898Z] [DEBUG] - [Assigned msgId = 6969500446203087400 to MsgsAck]
[2021-06-03T09:41:14.898Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-03T09:41:14.899Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-03T09:41:14.899Z] [DEBUG] - [Waiting for messages to send...false]
(node:1688) UnhandledPromiseRejectionWarning: Error: Could not create sender for DC 2
    at TelegramClient.<anonymous> (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:299:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1688) UnhandledPromiseRejectionWarning: Error: Could not create sender for DC 2
    at TelegramClient.<anonymous> (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:299:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\User\Desktop\telegramApi\node_modules\telegram\client\TelegramClient.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2021-06-03T09:41:14.902Z] [INFO] - [connection closed]
```

**Comment by painor** [comment]
what is your DC ?  can you also share a telegram link to the file that caused the issue ?

**Comment by MotionForward** [comment]
seems like DC 2, there is link https://t.me/testapi1234/14 for example image can`t be loaded, but with  https://t.me/testapi1234/13 it`s works

**Comment by painor** [comment]
very weird. I was able to download them just fine. but I am DC4. it seems like some connection issue from the logs you sent. I'll add a param to increase connection retries maybe that helps.

**Comment by MotionForward** [comment]
I feel like its something wrong with my telegram api app configuration, anyway thanks for help

**Comment by painor** [comment]
btw this should be fixed in the latest version. 1.7.1 feel free to try it out. it was an issue where telegram changed your main DC id but the string session wasn't updated.
