### ISSUE TITLE
RPCError: BOT_METHOD_INVALID

### ISSUE THREAD

**Issue by jiarongkoh** [gram-js/gramjs#93]
I'm attempting to get started with Telegram API using gramjs but can't seem to get beyond getting started. Specifically, I'm always thrown `BOT_METHOD_INVALID`.

```
const {TelegramClient, Api} = require('telegram');
const {StringSession} = require('telegram/sessions');

const apiId = "my_id"
const apiHash = "my_hash"
const stringSession = ''; 
const BOT_TOKEN = "my_bot_token";
const session = new StringSession('');
const client = new TelegramClient(session, apiId, apiHash, {connectionRetries: 5});

(async () => {
    await client.start({
        botAuthToken: BOT_TOKEN 
    })
    .then(() => {
        return run()
    })
    .catch((err) => {
        console.log("Err", err)
    })
})()

async function run() {
    let checkRequest = new Api.messages.CheckChatInvite({hash: "SOME_HASH"})
    const result = await client.invoke(checkRequest);
    console.log(result); 
};     
```

Error message:
```
[2021-06-05T09:35:24.880Z] [INFO] - [Signed in successfully as MYBOT]
Started...
[2021-06-05T09:35:24.880Z] [DEBUG] - [Assigned msgId = 6970241113245282760 to messages.CheckChatInvite]
[2021-06-05T09:35:24.880Z] [DEBUG] - [Encrypting 1 message(s) in 40 bytes for sending]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Assigned msgId = 6970241113253282180 to MsgsAck]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Encrypted messages put in a queue to be sent]
[2021-06-05T09:35:24.882Z] [DEBUG] - [Waiting for messages to send...false]
[2021-06-05T09:35:24.968Z] [DEBUG] - [Handling RPC result for message 6970241113245282760]
[2021-06-05T09:35:24.969Z] [DEBUG] - [Receiving items from the network...]
[2021-06-05T09:35:24.969Z] [DEBUG] - [Assigned msgId = 6970241113601282708 to MsgsAck]
[2021-06-05T09:35:24.969Z] [DEBUG] - [Encrypting 1 message(s) in 36 bytes for sending]
Err RPCError: BOT_METHOD_INVALID
    at Object.RPCMessageToError (MY_DIR/node_modules/telegram/errors/index.js:24:12)
    at MTProtoSender._handleRPCResult (MY_DIR/node_modules/telegram/network/MTProtoSender.js:488:36)
    at MTProtoSender.<anonymous> (MY_DIR/node_modules/telegram/network/MTProtoSender.js:412:19)
    at Generator.next (<anonymous>)
    at fulfilled (MY_DIR/node_modules/telegram/network/MTProtoSender.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined
}
```
I have checked that `CheckChatInvite` can be used by Bot.

I am using node 10 and telegram 1.6.10

**Comment by BLUE-DEVIL1134** [comment]
@jiarongkoh Please, next time before opening an issue make sure you are on the latest version of node and telegram.. :)
Upgrade to the 14th of the 16th version of node, the error should vanish.

**Comment by jiarongkoh** [comment]
Hi @BLUE-DEVIL1134, apologies. We use GCP, which currently supports up to v14 of node. v14 is the current LTS version. 

I have upgraded to node 14.17.0, but it still throws the same error. Do we need to use node 16?

**Comment by painor** [comment]
the issue has nothing to do with node. 
bot method invalid means that specific function cant be used by a bot and needs a user.

**Comment by jiarongkoh** [comment]
@painor then is the documentation outdated? The [docs](https://gram.js.org/tl/messages/CheckChatInvite#can-bots-use-this-method) indicate that bots can use this method.

**Comment by painor** [comment]
> @painor then is the documentation outdated? The [docs](https://gram.js.org/tl/messages/CheckChatInvite#can-bots-use-this-method) indicate that bots can use this method.

hmm seems like that's a bit outdated. I'll update it soon.

**Comment by painor** [comment]
should be updated.

**Comment by chanceDira** [comment]
Any Idea, how I can allow my bot to access iterMessages?

```
   const result = client.iterMessages(`@testten2024`, {
      limit: 20,
      reverse: false,
    });
```
